### ISSUE TITLE
Number of levels to obfuscate should be configurable

### ISSUE THREAD

**Issue by sandves** [hfurubotten/Heine.Mvc.ActionFilters#9]

**Comment by furier** [comment]
The obfuscation it self has no depth restrictions, but the `IObfuscaterService` which scans for properties to obfuscate on models do and need to be refactored. :)

**Comment by furier** [comment]
fått ordna dette nå? :P

**Comment by sandves** [comment]
@furier Nei, har ikke tid til sånn open source greier nå lenger :P
